# Generated by Django 5.1.1 on 2024-09-09 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.about')),
                ('my_blog', models.ManyToManyField(to='main_app.myblog')),
                ('projects', models.ManyToManyField(to='main_app.projects')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.resume')),
                ('services', models.ManyToManyField(to='main_app.services')),
                ('skills', models.ManyToManyField(to='main_app.skills')),
            ],
        ),
    ]
